### PR TITLE
Before destroy fix

### PR DESCRIPTION
**Pull request by DenisLapi**
### Fix or Enhancement?
Fix - prevent $destroy error if `this._chart` doesn't exist (if chart is not created)

- [x] All tests passed

### Environment
- OS: Ubuntu
- NPM Version: v3.5.2

### CODE REVIEW

**Comment by DenisLapi** [comment]
@apertureless Hey! I removed the files, now should be good I guess

**Comment by DenisLapi** [comment]
@apertureless Thank man! Is npm package updated now?

**Comment by apertureless** [comment]
The PR is not merged yet, as there are still merge conflicts. 
Will fix it later manually.

**Comment by apertureless** [comment]
It is merged.
You can now update over npm / npm-check / yarn upgrade-interactive to vue-chartjs@1.2.0

**Pull request merged**
