### PR TITLE
fix: update to chart.js v4.4.1

### PR DESCRIPTION
**Pull request by mihai-peteu**
Pulling in latest version of chart.js as a fix for https://github.com/apertureless/vue-chartjs/issues/1063

### CODE REVIEW

**Comment by adamdehaven** [comment]
@apertureless is this repo still maintained?

**Comment by apertureless** [comment]
@mihai-peteu 
Can you rebase? The CI should be fixed now.

**Comment by mihai-peteu** [comment]
@apertureless checks passed 🙌

**Comment by mihai-peteu** [comment]
Thanks!

Looks like the website workflow failed.

Does the [release workflow](https://github.com/apertureless/vue-chartjs/actions/workflows/release.yml) need to be run manually?  Would love to get this published to npm so we verify this fixes a bug we encountered.

**Comment by apertureless** [comment]
@mihai-peteu 
yeah, some pnpm shenanigans with the updated version. Not sure why this happens, as the lockfile should be updated.

The new version is released to npm.

**Pull request merged**
