### PR TITLE
Suggest Property Binding Usage in Docs/README.md

### PR DESCRIPTION
**Pull request by yuens1002**
### Fix or Enhancement?

- [ ] All tests passed

### Environment
- OS: Write here
- NPM Version: Write here

### CODE REVIEW

**Comment by apertureless** [comment]
Hi @yuens1002 ,

thanks for the PR. However I don't really understand your changes 🤔 
Because the way you changed this, it will not work.

The `width` and `height` props are `Numbers` in the [base charts](https://github.com/apertureless/vue-chartjs/blob/develop/src/BaseCharts/Doughnut.js#L30) but would be interpreted by Vue as strings if you pass them without `:`

The same for the options and data. If you pass your options like this `options="{responsive: true}"` it will be passed as a string. Not as an object.

**Comment by yuens1002** [comment]
I'll test this out again... But it did for me

**Comment by apertureless** [comment]
Thats interesting.
Normally it should throw an error. I will investigate further. 

I also wanted to update the examples if I find some time. Because in my experience people often copy paste the examples. But for production, props should be always defined with a type and default values, according to the official vue.js styleguide.

**Comment by yuens1002** [comment]
it throws the error in the console.... but the chart works fine.  i'll be
happy to rewrite the example by defining type/required...

**Comment by apertureless** [comment]
Ah, yeah that may be related to chartjs. Maybe it is interpreting the options always as an object. Dunno.

Sure feel free to.

**Pull request closed without merging**
