### PR TITLE
Remove default width and height

### LINKED ISSUE #503: Defaults for width and height breaks aspect ratio
### Expected Behavior
Not specifying a `width` or `height` should allow relying on responsive and aspectRatio to be respected.

### Actual Behavior
The defaults of `400` for `height` and `width` means that `aspectRatio` has no effect when set via options, it is always `400 / 400 = 1`. Manually setting `width` and `height` to `null` fixes the issue.

### Environment
- vue.js version: 2.5.17
- vue-chart.js version: 3.4.2
- yarn version: 1.15.2

### PR DESCRIPTION
**Pull request by jacobmischka**
Fixes #503

Admittedly, I didn't run any tests because I made this change online using the GitHub editor, apologies.

### CODE REVIEW

**Comment by Mach12** [comment]
Why is this not merged yet?? @apertureless

**Comment by apertureless** [comment]
Hi @Mach12 

this is not merged yet, because this will be a breaking change. And is planned to be rolled out together with some other changes in the reactivity mixins.

**Comment by Mach12** [comment]
Ah, I see. Waiting for 4.0.0 then.

**Comment by apertureless** [comment]
closed due to refactor

**Pull request closed without merging**
